### ISSUE TITLE
全キャスト勝率(全員)に新キャスト「リン」の勝率が反映されない

### ISSUE THREAD

**Issue by syara-temp** [syara-temp/wlw#1]
全キャスト勝率(全員)はキャストIDとキャストIDに対応するキャスト名をハードコーディングすることで計算対象の決定と、表示内容の制御を行っている。  

このため、Version 1.5 リリース時点で存在しなかった新キャスト「リン」に関しては、2015.05.19時点で全キャスト勝率(全員)に新キャスト「リン」の勝率は反映されない。

Version 1.xでは、新キャスト「リン」のキャストIDとキャスト名を他のキャストと同様にハードコーディングすることで対応する。  

Version 2.xでは、Cookieの保持データにキャスト名を含むようにし、1.xのハードコーディングによる記述部分を削除する。これにより新キャストの追加ごとに発生する対応を不要とする。

**Comment by syara-temp** [comment]
新キャスト「リン」のキャストIDの情報提供を求めています。

情報提供にご協力いただける方は、[Wonderland.NET](https://wonderland-wars.net/)にアクセスし、マイキャスト> 新キャスト「リン」を選択した後のURLを記載してください。

URL末尾のcast=(値)の"値"部分がキャストIDとなります。
以下は、ミクサ(キャストID=13)を選択した場合のURL例となります。
https://wonderland-wars.net/castdetail.html?cast=13

**Comment by yohei2112** [comment]
いつもお世話になっています
リンのキャストIDですがcast=45です

**Comment by syara-temp** [comment]
yohei2112様

情報提供ありがとうございます。
Version 1.6で修正版をリリースさせていただきました。
